In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import pickle 

# Surpress warnings:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

np.set_printoptions(precision=3, suppress=True)

In [16]:
boston=pickle.load(open('boston_housing_clean.pickle','rb'))
    
def plot_exponential_data():
    data = np.exp(np.random.normal(size=1000))
    plt.hist(data)
    plt.show()
    return data
    
def plot_square_normal_data():
    data = np.square(np.random.normal(loc=5, size=1000))
    plt.hist(data)
    plt.show()
    return data

In [17]:
boston.keys()

dict_keys(['dataframe', 'description'])

In [19]:
boston_data=boston['dataframe']
boston_description=boston['description']

In [20]:
boston_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [22]:
y_col='MEDV'
X=boston_data.drop(y_col,axis=1)
Y=boston_data[y_col]

In [24]:
from sklearn.preprocessing import StandardScaler 

s = StandardScaler()
X_ss=s.fit_transform(X)

In [25]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [27]:
a.mean(axis=0)

array([2.5, 3.5, 4.5])

In [28]:
a.mean(axis=1)

array([2., 5.])

In [29]:
X2=np.array(X)
man_transform=(X2-X2.mean(axis=0))/X2.std(axis=0)
np.allclose(man_transform,X_ss)

True

In [31]:
from sklearn.linear_model import LinearRegression 
lr=LinearRegression()
Y_col='MEDV'
X = boston_data.drop(Y_col, axis=1)
Y = boston_data[Y_col]

In [32]:
lr.fit(X,Y)
print(lr.coef_)

[ -0.107   0.046   0.021   2.689 -17.796   3.805   0.001  -1.476   0.306
  -0.012  -0.953   0.009  -0.525]


In [37]:
from sklearn.preprocessing import StandardScaler

s=StandardScaler()
X_ss=s.fit_transform(X)

In [38]:
lr2=LinearRegression()
lr2.fit(X_ss,Y)
print(lr2.coef_)

[-0.92   1.081  0.143  0.682 -2.06   2.671  0.021 -3.104  2.659 -2.076
 -2.062  0.857 -3.749]


In [43]:
pd.DataFrame(zip(X.columns.values,lr2.coef_)).sort_values(by=1)

0         1
12    LSTAT -3.748680
7       DIS -3.104448
9       TAX -2.075898
10  PTRATIO -2.062156
4       NOX -2.060092
0      CRIM -0.920411
6       AGE  0.021121
2     INDUS  0.142967
3      CHAS  0.682203
11        B  0.856640
1        ZN  1.080981
8       RAD  2.658787
5        RM  2.670641

In [44]:
from sklearn.linear_model import Lasso
from sklearn.preprocessing import PolynomialFeatures

In [46]:
pf=PolynomialFeatures(degree=2,include_bias=False,)
X_pf=pf.fit_transform(X)

In [47]:
X_pf_ss=s.fit_transform(X_pf)

In [48]:
lassor=Lasso()
lassor.fit(X_pf_ss,Y)
lassor.coef_

array([-0.   ,  0.   , -0.   ,  0.   , -0.   ,  0.   , -0.   , -0.   ,
       -0.   , -0.   , -0.991,  0.   , -0.   , -0.   ,  0.   , -0.   ,
        0.068, -0.   , -0.   , -0.   , -0.   , -0.   , -0.   , -0.   ,
       -0.   , -0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.   ,  0.   ,
       -0.   , -0.   , -0.   , -0.05 , -0.   , -0.   , -0.   , -0.   ,
       -0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   , -0.   , -0.   , -0.   , -0.   , -0.   ,
       -0.   , -0.   ,  0.   , -0.   ,  3.3  , -0.   , -0.   , -0.   ,
       -0.   , -0.   ,  0.42 , -3.498, -0.   , -0.   , -0.   , -0.   ,
       -0.   ,  0.   , -0.   , -0.   , -0.   , -0.146, -0.   , -0.   ,
       -0.   , -0.   , -0.   , -0.   , -0.   , -0.   , -0.   , -0.   ,
       -0.   , -0.   , -0.   ,  0.   , -0.   ,  0.   , -0.   , -0.   ])

In [49]:
lassor01=Lasso(alpha=0.1)
lassor01.fit(X_pf_ss,Y)
print('sum of the coefficients : ', abs(lassor01.coef_).sum())
print('number of coefficients not equal to 0 :' ,(lassor01.coef_!=0).sum())

sum of the coefficients :  26.17241511542676
number of coefficients not equal to 0 : 23


In [50]:
lassor1=Lasso(alpha=1)
lassor1.fit(X_pf_ss,Y)
print('sum of the coefficients : ', abs(lassor1.coef_).sum())
print('number of coefficients not equal to 0 :' ,(lassor1.coef_!=0).sum())

sum of the coefficients :  8.472405227760158
number of coefficients not equal to 0 : 7


In [51]:
from sklearn.metrics import r2_score
r2_score(Y,lassor.predict(X_pf_ss))

0.7207000461229028

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
X_train, X_test, Y_train, Y_test = train_test_split(X_pf, Y, test_size=0.3, 
                                                    random_state=72018)

In [56]:
X_train_s=s.fit_transform(X_train)
lassor.fit(X_train_s,Y_train)
X_test_s=s.transform(X_test)
Y_pred=lassor.predict(X_test_s)
r2_score(Y_pred,Y_test)

0.3318289609088583

In [57]:
X_train_s=s.fit_transform(X_train)
lassor01.fit(X_train_s,Y_train)
X_test_s=s.transform(X_test)
Y_pred=lassor01.predict(X_test_s)
r2_score(Y_pred,Y_test)

0.711227316581263

In [61]:
lassor001 = Lasso(alpha = 0.001, max_iter=100000)

X_train_s=s.fit_transform(X_train)
lassor001.fit(X_train_s,Y_train)
X_test_s=s.transform(X_test)
Y_pred=lassor001.predict(X_test_s)
print("r2 scorefor alpha =0.001: ", r2_score(Y_pred,Y_test))

lr = LinearRegression()

lr.fit(X_train_s,Y_train)
Y_pred_lr=lr.predict(X_test_s)
print("r2 score for linear regression: ", r2_score(Y_pred_lr,Y_test))

print('Magnitude of Lasso coefficients:', abs(lassor001.coef_).sum())
print('Number of coeffients not equal to 0 for Lasso:', (lassor001.coef_!=0).sum())

print('Magnitude of Linear Regression coefficients:', abs(lr.coef_).sum())
print('Number of coeffients not equal to 0 for Linear Regression:', (lr.coef_!=0).sum())


r2 scorefor alpha =0.001:  0.8688370609866953
r2 score for linear regression:  0.8558518908813423
Magnitude of Lasso coefficients: 435.572322904404
Number of coeffients not equal to 0 for Lasso: 90
Magnitude of Linear Regression coefficients: 1183.891813864888
Number of coeffients not equal to 0 for Linear Regression: 104


In [62]:
from sklearn.linear_model import Ridge

In [63]:
r = Ridge(alpha = 0.001)
X_train_s = s.fit_transform(X_train)
r.fit(X_train_s, Y_train)
X_test_s = s.transform(X_test)
Y_pred_r = r.predict(X_test_s)

In [64]:
r.coef_

array([  7.692,   9.889, -25.005,   5.31 ,  -2.61 ,  14.958,  22.314,
       -22.858,  27.765,  -1.565,  17.077,  21.858,  11.574,   1.05 ,
         0.431,  13.786,   1.814,  -8.345,   4.994,  -3.564,  -3.436,
       -16.336,  -7.047,   6.609,  -1.477,   4.686,  -1.304,  -0.059,
        -0.304, -12.842,   1.977,   1.081,  -0.676,  -1.079,   4.492,
        -4.267,   4.675,  -1.281,   8.666,  -0.274,  -8.12 ,  11.783,
         6.538,   1.323,   2.06 ,   0.899,   1.789,   4.744,  -4.664,
         5.31 ,  -3.236,  -8.668,   0.973,   1.136,   0.29 ,  -1.631,
        -2.926,   2.923,  -0.735,  11.896,   0.754,  -7.531,  18.306,
       -22.168,  35.651, -22.381,  -7.378,   1.732,   4.068, -12.254,
        -3.721,  -5.537, -16.169,  -5.872,  -4.515,  -9.903,   0.942,
        -0.095,  17.18 , -14.268,  -2.904,  -2.824,  -5.418,  11.908,
         0.065,  -4.433,  -5.679,  -3.515,   0.822, -29.082,  49.345,
       -21.72 ,  -1.428,  -8.864, -15.682,  11.982,  -0.818,   2.924,
        -0.701,  -4.

In [66]:
lassor001

Lasso(alpha=0.001, max_iter=100000)

In [68]:
lassor001.coef_

array([  0.   ,   0.   , -17.008,   2.592,   0.   ,  13.431,  10.062,
       -19.542,   9.237,   0.   ,   6.159,  17.087,  11.486,   1.208,
         0.219,  10.827,   2.185,  -7.106,   4.312,  -1.526,  -2.092,
        -9.669,   0.   ,   0.   ,  -1.177,   3.865,   0.378,   0.194,
        -0.296,  -3.478,   0.291,   0.72 ,  -0.795,  -0.74 ,   2.407,
        -0.892,   2.835,  -0.984,   3.864,  -0.963,   6.914,   6.2  ,
         4.197,   0.892,   2.028,   2.608,  -3.975,   2.574,  -4.568,
         2.086,  -2.   ,  -7.412,   1.604,   1.676,  -1.248,  -0.   ,
        -0.   ,   2.576,  -0.851,   3.206,  -0.   ,  -2.429,   9.276,
        -7.056,   0.   ,  -5.955,  -5.326,   0.531,   3.344,  -7.575,
        -0.   ,  -6.762, -10.2  ,  -6.428,  -2.835,  -9.561,   0.288,
         0.549,  11.094,  -6.731,  -1.161,  -2.301,  -3.555,   9.12 ,
        -0.014,  -2.384,  -2.042,  -1.691,   0.798, -20.822,  27.09 ,
         0.   ,  -1.527,  -6.793,  -5.084,  15.577,   0.   ,  -0.   ,
         0.569,  -3.

In [69]:
print(np.sum(np.abs(r.coef_)))
print(np.sum(np.abs(lassor001.coef_)))

print(np.sum(r.coef_ != 0))
print(np.sum(lassor001.coef_ != 0))

792.8673755128334
435.572322904404
104
90


In [73]:
Y_pred = r.predict(X_test_s)
print(r2_score(Y_test, Y_pred))

Y_pred = lassor001.predict(X_test_s)
print(r2_score(Y_test, Y_pred))

0.8702996266536451
0.8847893236874365


In [74]:
X_train, X_test, Y_train, Y_test = train_test_split(X_ss, Y, test_size=0.3, 
                                                    random_state=72018)

In [75]:
lr = LinearRegression()
lr.fit(X_train, Y_train)
Y_pred = lr.predict(X_test)
r2_score(Y_pred, Y_test)

0.5839451022507431

In [76]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, 
                                                    random_state=72018)

In [77]:
s = StandardScaler()
lr_s = LinearRegression()
X_train_s = s.fit_transform(X_train)
lr_s.fit(X_train_s, Y_train)
X_test_s = s.transform(X_test)
Y_pred_s = lr_s.predict(X_test_s)
r2_score(Y_pred_s, Y_test)

0.5839451022507429